export const FETCH_PLANETS = 'FETCH_PLANETS';
export const FETCH_VEHICLES = 'FETCH_VEHICLES';
export const STORE_SELECTED_PLANET = 'STORE_SELECTED_PLANET'
export const STORE_SELECTED_VEHCILE = 'STORE_SELECTED_VEHCILE'
export const GET_API_TOKEN = 'GET_API_TOKEN';
export const FIND_FALCONE = 'FIND_FALCONE';
export const RESET  = 'RESET';